---

- name: restart hostit-control
  ansible.builtin.systemd:
    name: hostit-control
    state: restarted
    daemon_reload: true

- name: restart hostit-node
  ansible.builtin.systemd:
    name: hostit-node
    state: restarted
    daemon_reload: true

- name: restart hostit-proxy
  ansible.builtin.systemd:
    name: hostit-proxy
    state: restarted
    daemon_reload: true

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
