---

- name: restart hostit-control
  systemd:
    name: hostit-control
    state: restarted
    daemon_reload: yes
  when: "'control' in hostit_components"

- name: restart hostit-node
  systemd:
    name: hostit-node
    state: restarted
    daemon_reload: yes
  when: "'node' in hostit_components"

- name: restart hostit-proxy
  systemd:
    name: hostit-proxy
    state: restarted
    daemon_reload: yes
  when: "'proxy' in hostit_components"

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
