package user

// publicMailProviders are domains anyone can get an address at. Allowing one as
// a sign-up domain does not open the instance to a company, it opens it to the
// internet, and an admin who does it by accident finds out later. The list only
// needs the providers people actually reach for; anything missed is still one
// admin decision away from being caught by the approval queue.
var publicMailProviders = map[string]bool{
	// Google, Microsoft, Apple, Yahoo
	"gmail.com":      true,
	"googlemail.com": true,
	"hotmail.com":    true,
	"hotmail.co.uk":  true,
	"hotmail.fr":     true,
	"hotmail.de":     true,
	"hotmail.it":     true,
	"outlook.com":    true,
	"outlook.de":     true,
	"live.com":       true,
	"live.co.uk":     true,
	"live.nl":        true,
	"msn.com":        true,
	"passport.com":   true,
	"icloud.com":     true,
	"me.com":         true,
	"mac.com":        true,
	"yahoo.com":      true,
	"yahoo.co.uk":    true,
	"yahoo.co.jp":    true,
	"yahoo.de":       true,
	"yahoo.fr":       true,
	"yahoo.in":       true,
	"ymail.com":      true,
	"rocketmail.com": true,
	"aol.com":        true,
	"aim.com":        true,
	"verizon.net":    true,
	"att.net":        true,
	"comcast.net":    true,
	"sbcglobal.net":  true,
	"bellsouth.net":  true,
	"cox.net":        true,
	"charter.net":    true,
	"earthlink.net":  true,
	"juno.com":       true,
	"optonline.net":  true,
	"frontier.com":   true,
	"windstream.net": true,

	// Privacy-focused and independent providers
	"proton.me":      true,
	"protonmail.com": true,
	"protonmail.ch":  true,
	"pm.me":          true,
	"tutanota.com":   true,
	"tutanota.de":    true,
	"tuta.io":        true,
	"tuta.com":       true,
	"fastmail.com":   true,
	"fastmail.fm":    true,
	"hushmail.com":   true,
	"zoho.com":       true,
	"zohomail.com":   true,
	"mailfence.com":  true,
	"posteo.de":      true,
	"mailbox.org":    true,
	"runbox.com":     true,
	"startmail.com":  true,

	// Europe
	"gmx.com":          true,
	"gmx.de":           true,
	"gmx.net":          true,
	"gmx.at":           true,
	"gmx.ch":           true,
	"web.de":           true,
	"t-online.de":      true,
	"freenet.de":       true,
	"arcor.de":         true,
	"orange.fr":        true,
	"wanadoo.fr":       true,
	"free.fr":          true,
	"laposte.net":      true,
	"sfr.fr":           true,
	"libero.it":        true,
	"virgilio.it":      true,
	"tiscali.it":       true,
	"alice.it":         true,
	"terra.com.br":     true,
	"uol.com.br":       true,
	"bol.com.br":       true,
	"seznam.cz":        true,
	"centrum.cz":       true,
	"wp.pl":            true,
	"onet.pl":          true,
	"o2.pl":            true,
	"interia.pl":       true,
	"telenet.be":       true,
	"ziggo.nl":         true,
	"kpnmail.nl":       true,
	"bluewin.ch":       true,
	"btinternet.com":   true,
	"virginmedia.com":  true,
	"sky.com":          true,
	"talktalk.net":     true,
	"blueyonder.co.uk": true,
	"ntlworld.com":     true,

	// Russia, Asia and elsewhere
	"mail.ru":        true,
	"inbox.ru":       true,
	"bk.ru":          true,
	"list.ru":        true,
	"internet.ru":    true,
	"yandex.ru":      true,
	"yandex.com":     true,
	"ya.ru":          true,
	"rambler.ru":     true,
	"qq.com":         true,
	"foxmail.com":    true,
	"163.com":        true,
	"126.com":        true,
	"sina.com":       true,
	"sina.cn":        true,
	"sohu.com":       true,
	"aliyun.com":     true,
	"naver.com":      true,
	"hanmail.net":    true,
	"daum.net":       true,
	"nate.com":       true,
	"docomo.ne.jp":   true,
	"ezweb.ne.jp":    true,
	"softbank.ne.jp": true,
	"rediffmail.com": true,
	"sify.com":       true,

	// Disposable and throwaway
	"mailinator.com":    true,
	"guerrillamail.com": true,
	"10minutemail.com":  true,
	"yopmail.com":       true,
	"temp-mail.org":     true,
	"trashmail.com":     true,
	"getnada.com":       true,
	"sharklasers.com":   true,
	"dispostable.com":   true,
	"maildrop.cc":       true,
	"throwawaymail.com": true,
	"tempmail.com":      true,
	"mailnesia.com":     true,
	"spamgourmet.com":   true,
	"emailondeck.com":   true,
}
